.github/workflows/AutoAssigneeAndReviewer.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #10
=> [CHORE] 오토리뷰어에 유현 계정 추가

src/main/java/com/doittogether/platform/business/stastics/StatisticsServiceImpl.java, src/main/java/com/doittogether/platform/domain/entity/Channel.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #19 
코드 컨벤션 진행
domain 패키지의 채널 엔티티에서 retrieve 함수를 제거하고 getter 어노테이션 사용하도록 변경하였습니다.
그리고 retrieve 함수를 사용한 부분을 get~()함수로 변경하였습니다.
=> refactor: 채널 도메인 리팩토링

src/main/java/com/doittogether/platform/business/channel/ChannelServiceImpl.java, src/main/java/com/doittogether/platform/common/oauth2/CustomAuthenticationSuccessHandler.java, src/main/java/com/doittogether/platform/common/oauth2/CustomOAuth2UserService.java, src/main/java/com/doittogether/platform/domain/entity/Assignee.java, src/main/java/com/doittogether/platform/domain/entity/User.java, src/main/java/com/doittogether/platform/presentation/dto/channel/response/ChannelKickUserResponse.java, src/main/java/com/doittogether/platform/presentation/dto/channel/response/ChannelListResponse.java, src/main/java/com/doittogether/platform/presentation/dto/channel/response/UserChannelResponse.java, src/main/java/com/doittogether/platform/presentation/dto/user/response/UserResponse.java, src/main/java/com/doittogether/platform/presentation/dto/user/response/UserUpdateResponse.java, src/test/java/com/doittogether/platform/business/channel/ChannelServiceTest.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #1 
@Getter 추가 및 retrieve 메서드 제거, service에서 retrieve -> get으로 변경
=> [REFACTOR] 회원 리펙토링

.github/workflows/AutoPRLabeler.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #21
=> [CHORE] 깃허브 토큰 환경변수 읽지 못하는 이슈 해결하기

src/main/java/com/doittogether/platform/business/stastics/StatisticsServiceImpl.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #25 
집안일 pr을 merge하는 과정에서 오타가 잘 못 들어가는 문제 발생
statistics 서비스 내의 오타 수정하였습니다.
=> [STYLE] statistics 서비스 오타 수정

.github/workflows/CD.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #27 
캐싱이 문젠가 싶어서 수정중입니다..
=> [CHORE] 캐싱 삭제

.github/workflows/AutoAssigneeAndReviewer.yml, .github/workflows/CD.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #29
=> [CHORE] yml 문법 오류로 인한 수정

.github/workflows/CD.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #31 
도커파일명이 이상했습니다,, 그래서 설정을 못먹었나봐요..
=> [CHORE] 도커파일 못찾는 문제 해결

src/main/java/com/doittogether/platform/common/config/SecurityConfig.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #34 
Security Config 설정에서 setAllowedOriginPatterns() 패턴 지정 수정
refactor : SecurityConfig CORS 오류 관련 패턴 수정
=> [FIX] config cors 설정 수정

src/main/java/com/doittogether/platform/business/channel/ChannelServiceImpl.java, src/main/java/com/doittogether/platform/business/user/UserServiceImpl.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #39 
유저 기능 관련 수정
refactor : 회원 탈퇴 기능 시 assignee 삭제 관련 수정
refactor : 회원 서비스에서 @Transaction 어노테이션 상위로 이동
refactor : 회원 서비스에서 @Transaction 어노테이션 상위로 이동에 따른 jpa save() 제거
=> [REFACTOR] 유저 도메인 기능 관련 수정

src/main/java/com/doittogether/platform/business/user/UserServiceImpl.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #43 
main 브랜치 컴파일 문법 오류 수정
=> [FIX] compile error 문법 오류 수정

src/main/java/com/doittogether/platform/presentation/controller/housework/HouseworkController.java, src/main/java/com/doittogether/platform/presentation/controller/housework/HouseworkControllerImpl.java
> #### 🔗 관련 이슈
> api 받는 값 중복 이슈
> 
> controller getMapping으로 작성 api받는값 수정
> close
=> [FIX] AI를 이용한 자동 담당자 조회 컨트롤러 수정

src/main/java/com/doittogether/platform/business/channel/ChannelService.java, src/main/java/com/doittogether/platform/business/channel/ChannelServiceImpl.java, src/main/java/com/doittogether/platform/business/user/UserServiceImpl.java, src/main/java/com/doittogether/platform/common/oauth2/filter/JwtAuthenticationFilter.java, src/main/java/com/doittogether/platform/domain/entity/Assignee.java, src/main/java/com/doittogether/platform/domain/entity/User.java, src/main/java/com/doittogether/platform/infrastructure/persistence/channel/UserChannelRepository.java, src/main/java/com/doittogether/platform/presentation/controller/channel/ChannelController.java, src/test/java/com/doittogether/platform/business/channel/ChannelServiceTest.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #48 
유저 탈퇴 리펙토링
refactor : 유저 탈퇴 과정에서 assignee Entity 의 foreign key 설정이 잘못 되있던 부분 수정(cascade 관련)
refactor : 유저 탈퇴 로직에서 트랜잭션 처리를 세부 항목으로 분류하여 처리되게 수정
refactor : 유저 엔티티에 assignee cascade 필드 추가
refactor : 채널 id index key 만큼 채널을 나갈 수 있도록 확장 메소드 추가
=> [REFACTOR] 유저 탈퇴 리펙토링(오류 수정 & 코드 개선)

src/main/java/com/doittogether/platform/application/global/code/ExceptionCode.java, src/main/java/com/doittogether/platform/business/channel/ChannelService.java, src/main/java/com/doittogether/platform/business/channel/ChannelServiceImpl.java, src/main/java/com/doittogether/platform/business/user/UserService.java, src/main/java/com/doittogether/platform/business/user/UserServiceImpl.java, src/main/java/com/doittogether/platform/domain/entity/Assignee.java, src/main/java/com/doittogether/platform/domain/entity/User.java, src/main/java/com/doittogether/platform/infrastructure/persistence/channel/UserChannelRepository.java, src/main/java/com/doittogether/platform/presentation/controller/channel/ChannelController.java, src/main/java/com/doittogether/platform/presentation/controller/personality/PersonalityController.java, src/test/java/com/doittogether/platform/business/channel/ChannelServiceTest.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #51 
특정 유저 사용자 성향 조회 API 기능 개발
feat : 특정 사용자에 대한 조회 및 연관 오류 메세지 처리용 조회 메소드 추가
feat : 특정 사용자의 성향 정보를 조회 기능 추가
refactor : 타겟 유저 관련 코드 정보를 사용자 관련으로 공통화
=> [FEAT] 특정 유저 사용자 성향 조회 API 구현

src/main/java/com/doittogether/platform/business/housework/HouseworkServiceImpl.java
> #### 🔗 관련 이슈
> Service 상 코드 오류
> 
> json에서 받는 키값이 없는데 설정해놔서 오류가 뜸
> close
=> [FIX] assignHouseworkFromGPT 오류수정

src/main/java/com/doittogether/platform/application/global/exception/ExceptionAdvice.java, src/main/java/com/doittogether/platform/common/config/WebConfig.java, src/main/java/com/doittogether/platform/common/config/interceptor/LoggingInterceptor.java, src/main/java/com/doittogether/platform/domain/entity/FcmToken.java, src/main/java/com/doittogether/platform/domain/enumeration/PlatformType.java, src/main/java/com/doittogether/platform/infrastructure/persistence/fcm/FcmTokenRepository.java, src/main/java/com/doittogether/platform/presentation/dto/fcm/SaveOrUpdateTokenRequest.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #53 
FCM 토큰 갱신 요청에서 여러 디바이스 정보를 저장할 수 있도록 수정
기타 오류 로그 관련 추가
refactor : 플랫폼 타입을 여러 형태로 저장될 수 있게 Entity 등 수정
refactor : 각 단계에서 로그 출력 추가
=> [FIX] FCM 디바이스 토큰 저장 이슈 수정

src/main/java/com/doittogether/platform/business/housework/HouseworkServiceImpl.java, src/main/java/com/doittogether/platform/business/openai/AssignChoreChatGPTService.java, src/main/java/com/doittogether/platform/infrastructure/persistence/housework/HouseworkRepository.java, src/main/java/com/doittogether/platform/presentation/dto/housework/HouseworkUserRequest.java
> #### 🔗 관련 이슈
> 프론트에서 houseworkId를 넘겨줄 수 없다는 요청이 있었음
> 
> houseworkId가 housework를 만드는 과정에는 생성이 되지 않는다고 하여 수정함.
> close
DTO의 값을 houseworkId -> houseworkName으로 변경하고 그에 따른 business 로직 수정
=> [FIX] request 값 변경 요청에 따른 service 수정

src/main/java/com/doittogether/platform/business/housework/HouseworkService.java, src/main/java/com/doittogether/platform/business/housework/HouseworkServiceImpl.java, src/main/java/com/doittogether/platform/business/openai/AssignChoreChatGPTService.java, src/main/java/com/doittogether/platform/business/openai/AssignChorePrompt.java, src/main/java/com/doittogether/platform/domain/entity/Assignee.java, src/main/java/com/doittogether/platform/domain/entity/Housework.java, src/main/java/com/doittogether/platform/infrastructure/persistence/housework/AssigneeRepository.java, src/main/java/com/doittogether/platform/presentation/dto/housework/HouseworkRequest.java, src/main/java/com/doittogether/platform/presentation/dto/housework/HouseworkUserResponse.java
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> [Fix] 로직 오류에 따른 코드 수정

src/main/java/com/doittogether/platform/domain/enumeration/AssigneeStatus.java
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> fix: 로직 오류에 따른 수정

src/main/java/com/doittogether/platform/business/housework/HouseworkServiceImpl.java, src/main/java/com/doittogether/platform/domain/entity/Housework.java, src/main/java/com/doittogether/platform/presentation/dto/housework/HouseworkRequest.java
> #### 🔗 관련 이슈
> DTO에 NOT NULL 부재
> 
> 
> close
=> [FIX] Request DTO 수정

src/main/java/com/doittogether/platform/business/channel/ChannelService.java, src/main/java/com/doittogether/platform/business/channel/ChannelServiceImpl.java, src/main/java/com/doittogether/platform/business/invite/InviteLinkService.java, src/main/java/com/doittogether/platform/business/invite/InviteLinkServiceImpl.java, src/main/java/com/doittogether/platform/presentation/controller/channel/ChannelController.java, src/main/resources/application.yml, src/test/java/com/doittogether/platform/business/channel/ChannelServiceTest.java, src/test/java/com/doittogether/platform/business/invite/InviteLinkServiceImplTest.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #64 
특정 채널에 대한 초대 링크의 ttl-minutes 를 따로 관리하기 위한 기능 추가
feat : 특정 채널 초대 링크 생성할 수 있는 api 구현(스웨거는 비공개)
chore : application.yml 에 초대링크 ttl test 관련 옵션 추가
test : 서비스 코드 변경에 따른 테스트 코드 수정
=> [FEAT] 초대 링크 테스트용 API 구현

src/main/java/com/doittogether/platform/business/invite/InviteLinkServiceImpl.java, src/main/java/com/doittogether/platform/common/config/EmbeddedRedisConfig.java, src/main/java/com/doittogether/platform/common/config/RedisConfig.java, src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #66 
1. Redis Config -> RedisStandaloneConfiguration 으로 설정 + Password 설정 강화
2. Redis 관련 로그 개선
refactor : Redis Config 설정 수정
refactor : Redis 관련 로그 개선
=> [REFACTOR] 레디스 설정 및 로그 수정

build.gradle
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> [CHORE] junit test 주석처리

build.gradle, src/main/java/com/doittogether/platform/DoItTogetherApplication.java, src/main/java/com/doittogether/platform/application/global/exception/ExceptionAdvice.java, src/main/java/com/doittogether/platform/business/discord/DiscordAlertSender.java, src/main/java/com/doittogether/platform/business/discord/DiscordErrorClientApi.java, src/main/java/com/doittogether/platform/business/discord/DiscordMessageGenerator.java, src/main/java/com/doittogether/platform/business/discord/DiscordSignUpClientApi.java, src/main/java/com/doittogether/platform/common/oauth2/CustomOAuth2UserService.java, src/main/java/com/doittogether/platform/presentation/dto/discord/DiscordEmbedDto.java, src/main/java/com/doittogether/platform/presentation/dto/discord/DiscordMessageDto.java, src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #70 
- 사용자 회원가입시,,
- 서버 에러 발생시
디스코드 알림 전송되도록 구현
- 회원가입시
- 에러발생시
리 동작 캡쳐 화면과 테스트 코드 통과 캡쳐 화면을 넣어주세요 -->
=> [FEAT] 디스코드 알림 기능 구현

.github/workflows/AutoAssigneeAndReviewer.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #72
=> [CHORE] 오토리뷰어 수정

src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> fix : ddl-auto 수정

src/main/java/com/doittogether/platform/business/invite/InviteLinkServiceImpl.java
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> [FIX] redis-key error 수정

src/main/java/com/doittogether/platform/common/config/DatabaseConfigLogger.java
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> [FIX] 데이터베이스 설정 확인 테스트

src/main/java/com/doittogether/platform/business/fcm/FcmService.java, src/main/java/com/doittogether/platform/business/fcm/FcmServiceImpl.java, src/main/java/com/doittogether/platform/presentation/controller/fcm/FcmController.java, src/main/java/com/doittogether/platform/presentation/dto/fcm/NotificationRequest.java, src/main/java/com/doittogether/platform/presentation/dto/reaction/CheckTokenRequest.java, src/main/java/com/doittogether/platform/presentation/dto/reaction/CheckTokenResponse.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #83 
feat : 유저 알림 토큰 활성화 체크 api 추가 
feat : 전송 데이터 추가(Map)
=> [FEAT] 유저 알림 토큰 활성화 체크 api 추가 및 전송 데이터 추가

src/main/java/com/doittogether/platform/application/global/exception/ExceptionAdvice.java, src/main/java/com/doittogether/platform/business/discord/DiscordAlertSender.java, src/main/java/com/doittogether/platform/common/oauth2/CustomOAuth2UserService.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #86 
디스코드 로그를 운영 환경에서만 동작되게 수정
=> [REFACTOR] 디스코드 prd 에서만 동작되게 수정

src/main/java/com/doittogether/platform/TestController.java, src/main/java/com/doittogether/platform/common/config/interceptor/LoggingInterceptor.java, src/main/java/com/doittogether/platform/common/config/wrapper/CachedBodyHttpServletRequest.java, src/main/java/com/doittogether/platform/common/oauth2/filter/JwtAuthenticationFilter.java, src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #89
=> [FEAT] 인터셉터를 통한 파라미터, URI 등의 로깅 강화

src/main/java/com/doittogether/platform/business/stastics/StatisticsServiceImpl.java, src/main/java/com/doittogether/platform/infrastructure/persistence/user/UserRepository.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #92 
이름으로 조회하면 쿼리 결과가 1개 일 걸로 예상되나 2개 이상이 조회될 수 있음 -> userId 조회로 변경
=> [FIX] 주간 통계 - 이번 주 완료 개수 랭킹 오류 수정

src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close
=> [FEAT] 디스코드 환경변수화

src/main/java/com/doittogether/platform/business/discord/DiscordAlertSender.java, src/main/resources/application.yml
> #### 🔗 관련 이슈
> 
> 
> 
> close #96 
1. application yml 잘못 설정 수정
2. 디스코드 런타임 오류 발생 시 APP 에 영향 주는 부분 수정
> 회원가입 시 discord url 이 옳바르지 않으면 오류가 발생하여 회원가입 오류 발생 되는 부분 때문
=> [FIX] 디스코드 런타임 오류 발생 시 APP 에 영향 주는 부분 수정

src/main/java/com/doittogether/platform/business/housework/HouseworkService.java, src/main/java/com/doittogether/platform/business/housework/HouseworkServiceImpl.java, src/main/java/com/doittogether/platform/business/stastics/StatisticsServiceImpl.java, src/main/java/com/doittogether/platform/infrastructure/persistence/housework/HouseworkRepository.java
> #### 🔗 관련 이슈
> 
> 
> 
> close #99 
주간 통계, 이번주 완료 개수 랭킹 조회 개수가 잘못 조회 되는 부분 수정
=> [FIX] 주간 통계, 이번주 완료 개수 랭킹 조회 오류 수정
